name: 流水线示例1
description: ""
global:
  concurrent: false
trigger:
  type: cron
  schedule: 0 30 14 * * ?
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: end
    name: 结束
    task: end
    needs:
      - git_log_0
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.5
    input:
      username: ((testgitea.user))
      password: ((testgitea.pwd))
      remote_url: '"https://testgitea2.trustie.net/gitgit/testdevops.git"'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 100
    needs:
      - start
  - ref: git_log_0
    name: git log
    task: git_log@1.0.2
    input:
      git_path: git_clone_0.git_path
      commit_num: 5
    needs:
      - git_clone_0

