name: 组织ownerclone私有仓库
description: ""
global:
  concurrent: false
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.5
    input:
      username: ((postman.user))
      password: ((postman.pwd))
      remote_url: '"https://testgitea2.trustie.net/test_jianmu_team/bot.git"'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 100
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - git_clone_0
