name: 给企业微信发送hello
description: ""
global:
  concurrent: false
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: qywx_notice_0
    name: 企业微信通知
    task: qywx_notice@1.2.1-text
    input:
      bot_webhook_url: ((wechat.wechat_bot))
      text_content: '"hello  this is message"'
      mentioned_list: '"[]"'
      mentioned_mobile_list: '"[]"'
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - qywx_notice_0

