name: 获取提交日志
description: ""
global:
  concurrent: false
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: git_log_0
    name: git log
    task: git_log@1.0.1
    input:
      git_path: https://testgitea2.trustie.net/gitgit/testdevops.git
      commit_num: 5
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - git_log_0

