name: 克隆项目,获取项目的log,向企业微信/钉钉发送消息
description: |-
  1. 第一步：克隆项目，指定commit id
  2. 第二步：获取克隆项目的指定次数的commit log
  3. 第三步：同时向钉钉/企业微信发送git_log
global:
  concurrent: false
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.4
    input:
      username: ((testgitea.user))
      password: ((testgitea.pwd))
      remote_url: '"https://testgitea2.trustie.net/gitgit/testdevops.git"'
      ref: '"refs/heads/master"'
      commit_id: '"c3e9c6bb1e"'
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - dingtalk_notice_action_card_0
      - qywx_notice_0
  - ref: git_log_0
    name: git log
    task: git_log@1.0.2
    input:
      git_path: git_clone_0.git_path
      commit_num: 5
    needs:
      - git_clone_0
  - ref: dingtalk_notice_action_card_0
    name: 钉钉通知-ActionCard
    task: dingtalk_notice_action_card@1.0.2
    input:
      boot_webhook_url: ((wecom.bot_webhook))
      msg_title: '"gitlog"'
      msg_text: git_log_0.git_log
      single_title: '""'
      single_url: '""'
      btns: '"[]"'
    needs:
      - git_log_0
  - ref: qywx_notice_0
    name: 企业微信通知
    task: qywx_notice@1.2.1-text
    input:
      bot_webhook_url: ((wechat.wechat_bot))
      text_content: JSON.stringify(git_log_0.git_log)
      mentioned_list: '"[]"'
      mentioned_mobile_list: '"[]"'
    needs:
      - git_log_0

